### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by ghost** [MSeys/sol2_ImGui_Bindings#1]
Hi,

First, thanks for your work.
And I find you sol_ImGui.h compile error with visual studio 2019 and [sol2](https://github.com/ThePhD/sol2/commit/f56b3c698c2116f41aad3bf731ba8400e68c498b).

I make some fix with https://gist.github.com/yinjimmy/6799641c2bf5b1e60048641d9ec6111f .

some modify:
1. move `G.ImGuiHoveredFlags` to `G.ImGui.ImGuiHoveredFlags` ;
2. `new_enum` -> `create_named`, then user can print the `key` of enums ;
3.

```
sol::as_table_t float2 = sol::as_table(std::vector<float>{
    value[0], value[1]
});
```

=>

```
auto float2 = std::vector<float>{value[0], value[1]};
```

Thanks,

**Comment by MSeys** [comment]
It seems Sol2 has updated a lot which makes my version not compile anymore. (It's from last July so it's been a good while)
I'm not sure if I can find the time to fix this however, it would be great if you could do a pull request which I can merge into this.
