### ISSUE TITLE
Usage and compile fix

### ISSUE THREAD

**Issue by Vali0004** [MSeys/sol2_ImGui_Bindings#2]
Seems like this does not compile, I modified the sol2 file types.hpp with one from a slightly older update and that seemed to fix it.
[types.txt](https://github.com/MSeys/sol2_ImGui_Bindings/files/7110555/types.txt)
Rename that to types.hpp but I have one question. How exactly is it called?
I use sol2 like this (just the example):
`
struct my_class {
		void Invis() {
			ENTITY::SET_ENTITY_VISIBLE(PLAYER::GET_PLAYER_PED(PLAYER::PLAYER_ID()), false, 0); //GTA 5 native
		}
	};
	sol::state lua;
	lua.open_libraries();
	sol_ImGui::Init(lua);
	auto bark = lua["bark"].get_or_create<sol::table>();
	bark.new_usertype<my_class>("Self",
		"Invis",
		&my_class::Invis);
	lua["Playername"] = PLAYER::GET_PLAYER_NAME(PLAYER::PLAYER_ID());
	lua.script(R"(
  ImGui.Begin("Name", true)
  ImGui.Text("Well hello there, General Kenobi")
  ImGui.End()
)");`
I seem to crash and can't figure out why. Could you help?

**Comment by MSeys** [comment]
Hi, this branch hasn't been updated for over a year due to not having the time, a few people forked it and updated theirs, it's best to look there.

Sorry for the inconvenience.

**Comment by Vali0004** [comment]
Could you give some links and I know. I just sent a fix to the stuff not compiling. I just need to know the LUA usage.

**Comment by MSeys** [comment]
Just going for a slightly older sol2, isn't going to help. The bindings themselves use an outdated sol2 (of over a year ago) and the way it's currently written, simply doesn't work or causes crashes.

You should go for a fork instead of this.

**Comment by Vali0004** [comment]
Do you have a fork? I can't find any.

**Comment by MSeys** [comment]
I updated the readme with a direct link to the forks, which you can also find through github itself. I hope you find a working version.
